spring.datasource.name=MIC
spring.datasource.url=jdbc:mysql://localhost:3306/MIC
spring.datasource.username=root
spring.datasource.password=Kartikpatil1212
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=3232
spring.jpa.hibernate.ddl-auto=update